// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBAmcbO-I0qfHJqvmGkIurOVGKfMHSBIs',
    appId: '1:87504906995:web:7efb516e69090a7d9aa586',
    messagingSenderId: '87504906995',
    projectId: 'blood-sharing-app',
    authDomain: 'blood-sharing-app.firebaseapp.com',
    storageBucket: 'blood-sharing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb25otEfbPiwhz9Zbb9b8WHib7CQG-3cg',
    appId: '1:87504906995:android:1c2228e89579aa689aa586',
    messagingSenderId: '87504906995',
    projectId: 'blood-sharing-app',
    storageBucket: 'blood-sharing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-E1EDwGnrTz-UaVLuhbYrsIqQevNDYGk',
    appId: '1:87504906995:ios:9f3818c2c4e9959c9aa586',
    messagingSenderId: '87504906995',
    projectId: 'blood-sharing-app',
    storageBucket: 'blood-sharing-app.firebasestorage.app',
    iosBundleId: 'com.example.bloodSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-E1EDwGnrTz-UaVLuhbYrsIqQevNDYGk',
    appId: '1:87504906995:ios:9f3818c2c4e9959c9aa586',
    messagingSenderId: '87504906995',
    projectId: 'blood-sharing-app',
    storageBucket: 'blood-sharing-app.firebasestorage.app',
    iosBundleId: 'com.example.bloodSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBAmcbO-I0qfHJqvmGkIurOVGKfMHSBIs',
    appId: '1:87504906995:web:6b20a6886f30a08a9aa586',
    messagingSenderId: '87504906995',
    projectId: 'blood-sharing-app',
    authDomain: 'blood-sharing-app.firebaseapp.com',
    storageBucket: 'blood-sharing-app.firebasestorage.app',
  );
}
